version: '3.9'
services:
  mongodb:
    container_name: mongoc
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db  
  mongo-express:
    container_name: mongoexpc
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped

  nodejs-app:
    container_name: product-appc
    image: ayoubyte/products-store-nodejs-app:1.4
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    stdin_open: true
    tty: true

volumes:
  mongo-data:
    driver: local




    